name: Ubuntu Build & Deploy

on:
  workflow_dispatch:   # 允许手动触发
  push:
    branches: [main]   # 推送到 main 分支时自动触发

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest  # 使用 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # 指定 Node.js 版本

      - name: Install Yarn
        run: npm install -g yarn  # 通过 npm 安装 Yarn

      - name: Cache Yarn dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            .yarn/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile  # 锁定依赖版本

      - name: Build project
        run: yarn build

      - name: Verify build output
        run: ls -R dist  # 检查构建产物（Linux 命令）

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-output
          path: dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true  # 强制清空历史，避免 Git 冲突
